import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import '@fontsource-variable/montserrat';
import '@fontsource-variable/raleway';
import '@fontsource-variable/cinzel';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <NextUIProvider>
          <Nav />
          {children}
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
